import Joi from 'joi';

export const createPatientSchema = Joi.object({
  name: Joi.string().required(),
  email: Joi.string().email().allow('', null),
  phone: Joi.string().allow('', null),
  cpf: Joi.string().allow('', null),
  rg: Joi.string().allow('', null),
  date_of_birth: Joi.string().pattern(/^\d{4}-\d{2}-\d{2}$/).allow(null),
  nationality: Joi.string().allow('', null),
  naturality: Joi.string().allow('', null),
  cep: Joi.string().allow('', null),
  state: Joi.string().allow('', null),
  city: Joi.string().allow('', null),
  street: Joi.string().allow('', null),
  number: Joi.string().allow('', null),
  complement: Joi.string().allow('', null),
  responsible_name: Joi.string().allow('', null),
  responsible_cpf: Joi.string().allow('', null),
  responsible_phone: Joi.string().allow('', null),
  medic_history: Joi.string().allow('', null),
  observations: Joi.string().allow('', null),
  active: Joi.boolean(),
});

export const updatePatientSchema = Joi.object({
  name: Joi.string(),
  email: Joi.string().email().allow('', null),
  phone: Joi.string().allow('', null),
  cpf: Joi.string().allow('', null),
  rg: Joi.string().allow('', null),
  date_of_birth: Joi.string().pattern(/^\d{4}-\d{2}-\d{2}$/).allow(null),
  nationality: Joi.string().allow('', null),
  naturality: Joi.string().allow('', null),
  cep: Joi.string().allow('', null),
  state: Joi.string().allow('', null),
  city: Joi.string().allow('', null),
  street: Joi.string().allow('', null),
  number: Joi.string().allow('', null),
  complement: Joi.string().allow('', null),
  responsible_name: Joi.string().allow('', null),
  responsible_cpf: Joi.string().allow('', null),
  responsible_phone: Joi.string().allow('', null),
  medic_history: Joi.string().allow('', null),
  observations: Joi.string().allow('', null),
  active: Joi.boolean(),
});
